### ISSUE TITLE
can you use frameworks like vue,react?

### ISSUE THREAD

**Issue by zhuewizz** [nuxy/go-webview-app-builder#1]
Great work, can you use frameworks like vue,react? Is there a simple example?

**Comment by nuxy** [comment]
Yes, this should support **any JavaScript framework**.  However, no examples are available since _it's mostly custom integration_. 

I recently [updated](https://github.com/nuxy/go-webview-app-builder/blob/master/README.md#does-this-support-other-javascript-frameworks) the project `README.md` to briefly cover this topic.  Hope this helps.
